/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.25.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateJobRequestOneOfAllOfParams {
    SamplerV2Input(Box<models::SamplerV2Input>),
    EstimatorV2Input(Box<models::EstimatorV2Input>),
    NoiseLearnerInput(Box<models::NoiseLearnerInput>),
}

impl Default for CreateJobRequestOneOfAllOfParams {
    fn default() -> Self {
        Self::SamplerV2Input(Default::default())
    }
}
/// For NoiseLearner, should always be 2
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "2")]
    Variant2,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant2
    }
}
/// How much resilience to build against errors
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResilienceLevel {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
}

impl Default for ResilienceLevel {
    fn default() -> ResilienceLevel {
        Self::Variant0
    }
}
