/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.23.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplerV2InputPubsInner {
    __type__: String,
    __value__: String,
}

impl SamplerV2InputPubsInner {
    pub fn new(qpy_string: String) -> SamplerV2InputPubsInner {
        SamplerV2InputPubsInner {
            __type__: "QuantumCircuit".to_string(),
            __value__: qpy_string,
        }
    }
}
